config/routes.rb
Rails.application.routes.draw do
  resources :relaciona_con_normas
  resources :tipo_relacions
  resources :cambio_aplicados
  resources :cambio_estados
  resources :causa_cambio_estados
  resources :logins
  resources :agregar_privilegios
  resources :patron_privilegios
  resources :tiene_privilegios
  resources :privilegios
  resources :usuarios
  resources :posee_desc_parts
  resources :posee_descriptors
  resources :normas
  resources :tipo_normas
  resources :descriptor_particulars
  resources :descriptor_generals
  resources :lugar_publicacions
  resources :estados
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pagina_principal', to: 'pagina_principal#index'
  get 'banner', to: 'banner#index'
  get 'cambio_estados_a_vencer', to: 'cambio_estados_a_vencer#index'

  get 'buscar_por_descriptores', to: 'buscar_desc_part#index'
  get 'buscar_por_descriptores/index'
  get 'buscar_por_descriptores/buscar_desc_part'
  get 'buscar_por_descriptores/elegir_desc_part'
  get 'buscar_por_descriptores/otras_opciones'
  get 'buscar_por_descriptores/buscar_normas'
  get 'buscar_por_descriptores/vista_impresion'

  get 'buscar_por_fecha', to: 'buscar_por_fecha#index'
  get 'buscar_por_fecha/index'
  get 'buscar_por_fecha/resultados'
  get 'buscar_por_fecha/vista_impresion'

  get 'buscar_por_texto', to: 'buscar_por_texto#index'
  get 'buscar_por_texto/index'
  get 'buscar_por_texto/buscar_texto'
  get 'buscar_por_texto/vista_impresion'  
  
  get 'buscar_por_numero', to: 'buscar_por_numero#index'
  get 'buscar_por_numero/index'
  get 'buscar_por_numero/buscar_numero'
  get 'buscar_por_numero/vista_impresion'

  get 'ultimas_normas', to: 'ultimas_normas#index'

  get 'nueva_norma', to: 'nueva_norma#index'
  get 'nueva_norma/guardar_norma'
  get 'nueva_norma/agregar_comentarios'
  get 'nueva_norma/guardar_comentarios'
  get 'nueva_norma/agregar_citas'
  get 'nueva_norma/guardar_citas'
  get 'nueva_norma/subir_texto'
  get 'nueva_norma/guardar_texto'
  get 'nueva_norma/planificar_vencimientos'
  get 'nueva_norma/planificar'
  get 'nueva_norma/otro_plan'
  get 'nueva_norma/crear_relaciones'
  get 'nueva_norma/guardar_relacion'
  get 'nueva_norma/otra_relacion'

  get 'modificar_norma', to: 'modificar_norma#index'
  get 'modificar_norma/buscar_norma'
  get 'modificar_norma/modificar_norma'

  get 'agregar_descriptores', to: 'agregar_descriptores#index'
  get 'agregar_descriptores/seleccionar_desc_gen'
  get 'agregar_descriptores/agregar_desc_gen'
  get 'agregar_descriptores/seleccionar_desc_part'
  get 'agregar_descriptores/agregar_desc_part'
  get 'agregar_descriptores/otro'

  get 'quitar_descriptor', to: 'quitar_descriptor#index'
  get 'quitar_descriptor/quitar_desc_gen'
  get 'quitar_descriptor/quitar_desc_part'
  get 'quitar_descriptor/eliminar_posee_desc'

  get 'asignar_privilegios', to: 'asignar_privilegios#index'
  get 'asignar_privilegios/asignar_patron'
  get 'asignar_privilegios/aplicar_privilegios'
  get 'asignar_privilegios/agregar_privilegios'

  get 'logout', to: 'logout#index'
  
  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
end

app/models/tipo_norma.rb
# -*- coding: utf-8 -*-

# tipo_norma.rb
# Copyright (C) 2010  Giménez, Christian N.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Jueves 07 De Octubre Del 2010    

class TipoNorma < ApplicationRecord
  #Privilegios:
  PuedeCrear = "Crear Tipo de Normas"
  PuedeConsultar = "Consultar Tipo de Normas"
  PuedeEditar = "Editar Tipo de Normas"
  PuedeEliminar = "Eliminar Tipo de Normas"

  #Vease el diagrama DIA y SQL
  has_many :normas

  validates_presence_of(:nombre, :message => "¡Debe escribir un nombre!")
  validates_uniqueness_of(:nombre, :message => "¡Ese nombre ya existe!")
end

app/controllers/tipo_normas_controller.rb
class TipoNormasController < ApplicationController
  before_action :set_tipo_norma, only: [:show, :edit, :update, :destroy]

  # GET /tipo_normas
  # GET /tipo_normas.json
  def index
    @tipo_normas = TipoNorma.all
  end

  # GET /tipo_normas/1
  # GET /tipo_normas/1.json
  def show
  end

  # GET /tipo_normas/new
  def new
    @tipo_norma = TipoNorma.new
  end

  # GET /tipo_normas/1/edit
  def edit
  end

  # POST /tipo_normas
  # POST /tipo_normas.json
  def create
    @tipo_norma = TipoNorma.new(tipo_norma_params)

    respond_to do |format|
      if @tipo_norma.save
        format.html { redirect_to @tipo_norma, notice: 'Tipo norma was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_norma }
      else
        format.html { render :new }
        format.json { render json: @tipo_norma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_normas/1
  # PATCH/PUT /tipo_normas/1.json
  def update
    respond_to do |format|
      if @tipo_norma.update(tipo_norma_params)
        format.html { redirect_to @tipo_norma, notice: 'Tipo norma was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_norma }
      else
        format.html { render :edit }
        format.json { render json: @tipo_norma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_normas/1
  # DELETE /tipo_normas/1.json
  def destroy
    @tipo_norma.destroy
    respond_to do |format|
      format.html { redirect_to tipo_normas_url, notice: 'Tipo norma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_norma
      @tipo_norma = TipoNorma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_norma_params
      params.require(:tipo_norma).permit(:nombre, :comentario)
    end
end

app/helpers/tipo_normas_helper.rb
module TipoNormasHelper
end

app/views/tipo_normas/_form.html.erb
<%= form_with(model: tipo_norma, local: true) do |form| %>
  <% if tipo_norma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_norma.errors.count, "error") %> prohibited this tipo_norma from being saved:</h2>

      <ul>
      <% tipo_norma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_area :comentario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipo_normas/edit.html.erb
<h1>Editing Tipo Norma</h1>

<%= render 'form', tipo_norma: @tipo_norma %>

<%= link_to 'Show', @tipo_norma %> |
<%= link_to 'Back', tipo_normas_path %>

app/views/tipo_normas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Normas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_normas.each do |tipo_norma| %>
      <tr>
        <td><%= tipo_norma.nombre %></td>
        <td><%= tipo_norma.comentario %></td>
        <td><%= link_to 'Show', tipo_norma %></td>
        <td><%= link_to 'Edit', edit_tipo_norma_path(tipo_norma) %></td>
        <td><%= link_to 'Destroy', tipo_norma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Norma', new_tipo_norma_path %>

app/views/tipo_normas/new.html.erb
<h1>New Tipo Norma</h1>

<%= render 'form', tipo_norma: @tipo_norma %>

<%= link_to 'Back', tipo_normas_path %>

app/views/tipo_normas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_norma.nombre %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @tipo_norma.comentario %>
</p>

<%= link_to 'Edit', edit_tipo_norma_path(@tipo_norma) %> |
<%= link_to 'Back', tipo_normas_path %>