config/routes.rb
Rails.application.routes.draw do
  resources :relaciona_con_normas
  resources :tipo_relacions
  resources :cambio_aplicados
  resources :cambio_estados
  resources :causa_cambio_estados
  resources :logins
  resources :agregar_privilegios
  resources :patron_privilegios
  resources :tiene_privilegios
  resources :privilegios
  resources :usuarios
  resources :posee_desc_parts
  resources :posee_descriptors
  resources :normas
  resources :tipo_normas
  resources :descriptor_particulars
  resources :descriptor_generals
  resources :lugar_publicacions
  resources :estados
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pagina_principal', to: 'pagina_principal#index'
  get 'banner', to: 'banner#index'
  get 'cambio_estados_a_vencer', to: 'cambio_estados_a_vencer#index'

  get 'buscar_por_descriptores', to: 'buscar_desc_part#index'
  get 'buscar_por_descriptores/index'
  get 'buscar_por_descriptores/buscar_desc_part'
  get 'buscar_por_descriptores/elegir_desc_part'
  get 'buscar_por_descriptores/otras_opciones'
  get 'buscar_por_descriptores/buscar_normas'
  get 'buscar_por_descriptores/vista_impresion'

  get 'buscar_por_fecha', to: 'buscar_por_fecha#index'
  get 'buscar_por_fecha/index'
  get 'buscar_por_fecha/resultados'
  get 'buscar_por_fecha/vista_impresion'

  get 'buscar_por_texto', to: 'buscar_por_texto#index'
  get 'buscar_por_texto/index'
  get 'buscar_por_texto/buscar_texto'
  get 'buscar_por_texto/vista_impresion'  
  
  get 'buscar_por_numero', to: 'buscar_por_numero#index'
  get 'buscar_por_numero/index'
  get 'buscar_por_numero/buscar_numero'
  get 'buscar_por_numero/vista_impresion'

  get 'ultimas_normas', to: 'ultimas_normas#index'

  get 'nueva_norma', to: 'nueva_norma#index'
  get 'nueva_norma/guardar_norma'
  get 'nueva_norma/agregar_comentarios'
  get 'nueva_norma/guardar_comentarios'
  get 'nueva_norma/agregar_citas'
  get 'nueva_norma/guardar_citas'
  get 'nueva_norma/subir_texto'
  get 'nueva_norma/guardar_texto'
  get 'nueva_norma/planificar_vencimientos'
  get 'nueva_norma/planificar'
  get 'nueva_norma/otro_plan'
  get 'nueva_norma/crear_relaciones'
  get 'nueva_norma/guardar_relacion'
  get 'nueva_norma/otra_relacion'

  get 'modificar_norma', to: 'modificar_norma#index'
  get 'modificar_norma/buscar_norma'
  get 'modificar_norma/modificar_norma'

  get 'agregar_descriptores', to: 'agregar_descriptores#index'
  get 'agregar_descriptores/seleccionar_desc_gen'
  get 'agregar_descriptores/agregar_desc_gen'
  get 'agregar_descriptores/seleccionar_desc_part'
  get 'agregar_descriptores/agregar_desc_part'
  get 'agregar_descriptores/otro'

  get 'quitar_descriptor', to: 'quitar_descriptor#index'
  get 'quitar_descriptor/quitar_desc_gen'
  get 'quitar_descriptor/quitar_desc_part'
  get 'quitar_descriptor/eliminar_posee_desc'

  get 'asignar_privilegios', to: 'asignar_privilegios#index'
  get 'asignar_privilegios/asignar_patron'
  get 'asignar_privilegios/aplicar_privilegios'
  get 'asignar_privilegios/agregar_privilegios'

  get 'logout', to: 'logout#index'
  
  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
end

app/models/lugar_publicacion.rb
# -*- coding: utf-8 -*-

# lugar_publicacion.rb
# Copyright (C) 2010  Giménez, Christian N.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Jueves 07 De Octubre Del 2010    

class LugarPublicacion < ApplicationRecord
  #Privilegios:
  PuedeCrear = "Crear Lugar de Publicaciones"
  PuedeConsultar = "Consultar Lugar de Publicaciones"
  PuedeEditar = "Editar Lugar de Publicaciones"
  PuedeEliminar = "Eliminar Lugar de Publicaciones"
  
  #Vea el modelo DIA y SQL
  has_many :normas

  #Valida que tenga un nombre y que sea único.
  validates_presence_of(:nombre, :message => "¡Debe escribir un nombre!")
  validates_uniqueness_of(:nombre, :message => "¡Ese nombre ya existe!")
end

app/controllers/lugar_publicacions_controller.rb
class LugarPublicacionsController < ApplicationController
  before_action :set_lugar_publicacion, only: [:show, :edit, :update, :destroy]

  # GET /lugar_publicacions
  # GET /lugar_publicacions.json
  def index
    @lugar_publicacions = LugarPublicacion.all
  end

  # GET /lugar_publicacions/1
  # GET /lugar_publicacions/1.json
  def show
  end

  # GET /lugar_publicacions/new
  def new
    @lugar_publicacion = LugarPublicacion.new
  end

  # GET /lugar_publicacions/1/edit
  def edit
  end

  # POST /lugar_publicacions
  # POST /lugar_publicacions.json
  def create
    @lugar_publicacion = LugarPublicacion.new(lugar_publicacion_params)

    respond_to do |format|
      if @lugar_publicacion.save
        format.html { redirect_to @lugar_publicacion, notice: 'Lugar publicacion was successfully created.' }
        format.json { render :show, status: :created, location: @lugar_publicacion }
      else
        format.html { render :new }
        format.json { render json: @lugar_publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugar_publicacions/1
  # PATCH/PUT /lugar_publicacions/1.json
  def update
    respond_to do |format|
      if @lugar_publicacion.update(lugar_publicacion_params)
        format.html { redirect_to @lugar_publicacion, notice: 'Lugar publicacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugar_publicacion }
      else
        format.html { render :edit }
        format.json { render json: @lugar_publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugar_publicacions/1
  # DELETE /lugar_publicacions/1.json
  def destroy
    @lugar_publicacion.destroy
    respond_to do |format|
      format.html { redirect_to lugar_publicacions_url, notice: 'Lugar publicacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lugar_publicacion
      @lugar_publicacion = LugarPublicacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lugar_publicacion_params
      params.require(:lugar_publicacion).permit(:nombre, :comentario)
    end
end

app/helpers/lugar_publicacions_helper.rb
module LugarPublicacionsHelper
end

app/views/lugar_publicacions/_form.html.erb
<%= form_with(model: lugar_publicacion, local: true) do |form| %>
  <% if lugar_publicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lugar_publicacion.errors.count, "error") %> prohibited this lugar_publicacion from being saved:</h2>

      <ul>
      <% lugar_publicacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_area :comentario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lugar_publicacions/edit.html.erb
<h1>Editing Lugar Publicacion</h1>

<%= render 'form', lugar_publicacion: @lugar_publicacion %>

<%= link_to 'Show', @lugar_publicacion %> |
<%= link_to 'Back', lugar_publicacions_path %>

app/views/lugar_publicacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lugar Publicacions</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lugar_publicacions.each do |lugar_publicacion| %>
      <tr>
        <td><%= lugar_publicacion.nombre %></td>
        <td><%= lugar_publicacion.comentario %></td>
        <td><%= link_to 'Show', lugar_publicacion %></td>
        <td><%= link_to 'Edit', edit_lugar_publicacion_path(lugar_publicacion) %></td>
        <td><%= link_to 'Destroy', lugar_publicacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lugar Publicacion', new_lugar_publicacion_path %>

app/views/lugar_publicacions/new.html.erb
<h1>New Lugar Publicacion</h1>

<%= render 'form', lugar_publicacion: @lugar_publicacion %>

<%= link_to 'Back', lugar_publicacions_path %>

app/views/lugar_publicacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @lugar_publicacion.nombre %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @lugar_publicacion.comentario %>
</p>

<%= link_to 'Edit', edit_lugar_publicacion_path(@lugar_publicacion) %> |
<%= link_to 'Back', lugar_publicacions_path %>