config/routes.rb
Rails.application.routes.draw do
  resources :relaciona_con_normas
  resources :tipo_relacions
  resources :cambio_aplicados
  resources :cambio_estados
  resources :causa_cambio_estados
  resources :logins
  resources :agregar_privilegios
  resources :patron_privilegios
  resources :tiene_privilegios
  resources :privilegios
  resources :usuarios
  resources :posee_desc_parts
  resources :posee_descriptors
  resources :normas
  resources :tipo_normas
  resources :descriptor_particulars
  resources :descriptor_generals
  resources :lugar_publicacions
  resources :estados
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pagina_principal', to: 'pagina_principal#index'
  get 'banner', to: 'banner#index'
  get 'cambio_estados_a_vencer', to: 'cambio_estados_a_vencer#index'

  get 'buscar_por_descriptores', to: 'buscar_desc_part#index'
  get 'buscar_por_descriptores/index'
  get 'buscar_por_descriptores/buscar_desc_part'
  get 'buscar_por_descriptores/elegir_desc_part'
  get 'buscar_por_descriptores/otras_opciones'
  get 'buscar_por_descriptores/buscar_normas'
  get 'buscar_por_descriptores/vista_impresion'

  get 'buscar_por_fecha', to: 'buscar_por_fecha#index'
  get 'buscar_por_fecha/index'
  get 'buscar_por_fecha/resultados'
  get 'buscar_por_fecha/vista_impresion'

  get 'buscar_por_texto', to: 'buscar_por_texto#index'
  get 'buscar_por_texto/index'
  get 'buscar_por_texto/buscar_texto'
  get 'buscar_por_texto/vista_impresion'  
  
  get 'buscar_por_numero', to: 'buscar_por_numero#index'
  get 'buscar_por_numero/index'
  get 'buscar_por_numero/buscar_numero'
  get 'buscar_por_numero/vista_impresion'

  get 'ultimas_normas', to: 'ultimas_normas#index'

  get 'nueva_norma', to: 'nueva_norma#index'
  get 'nueva_norma/guardar_norma'
  get 'nueva_norma/agregar_comentarios'
  get 'nueva_norma/guardar_comentarios'
  get 'nueva_norma/agregar_citas'
  get 'nueva_norma/guardar_citas'
  get 'nueva_norma/subir_texto'
  get 'nueva_norma/guardar_texto'
  get 'nueva_norma/planificar_vencimientos'
  get 'nueva_norma/planificar'
  get 'nueva_norma/otro_plan'
  get 'nueva_norma/crear_relaciones'
  get 'nueva_norma/guardar_relacion'
  get 'nueva_norma/otra_relacion'

  get 'modificar_norma', to: 'modificar_norma#index'
  get 'modificar_norma/buscar_norma'
  get 'modificar_norma/modificar_norma'

  get 'agregar_descriptores', to: 'agregar_descriptores#index'
  get 'agregar_descriptores/seleccionar_desc_gen'
  get 'agregar_descriptores/agregar_desc_gen'
  get 'agregar_descriptores/seleccionar_desc_part'
  get 'agregar_descriptores/agregar_desc_part'
  get 'agregar_descriptores/otro'

  get 'quitar_descriptor', to: 'quitar_descriptor#index'
  get 'quitar_descriptor/quitar_desc_gen'
  get 'quitar_descriptor/quitar_desc_part'
  get 'quitar_descriptor/eliminar_posee_desc'

  get 'asignar_privilegios', to: 'asignar_privilegios#index'
  get 'asignar_privilegios/asignar_patron'
  get 'asignar_privilegios/aplicar_privilegios'
  get 'asignar_privilegios/agregar_privilegios'

  get 'logout', to: 'logout#index'
  
  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
end

app/models/posee_desc_part.rb
# -*- coding: utf-8 -*-

# posee_desc_part.rb
# Copyright (C) 2010  Giménez, Christian N.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Jueves 07 De Octubre Del 2010    

class PoseeDescPart < ApplicationRecord
  #Privilegios:
  PuedeCrear = "Crear Posee DescParts"
  PuedeConsultar = "Consultar Posee DescParts"
  PuedeEditar = "Editar Posee DescParts"
  PuedeEliminar = "Eliminar Posee DescParts"

  belongs_to :norma
  belongs_to :descriptor_particular

  #Verificar que tenga una norma y un descriptor particular.
  validates_presence_of(:norma, :message => "¡Debe escribir una norma válida")
  validates_presence_of(:descriptor_particular ,
                        :message => "¡Debe escribir un descriptor válido!")
  #Verificar que sólo haya una relación de una norma a un descriptor particular.
  #Contra-ejemplo:
  #  norma1 => descPart1  (BIEN HASTA AQUÍ)
  #  norma1 => descPart2  (BIEN)
  #  norma1 => descPart1  (¡MAL! ¡YA EXISTE!)
  validates_uniqueness_of(
    :norma_id,
    :scope => [:descriptor_particular_id],
    :message => "¡Ya existe esa norma relacionada con ese descriptor!")

  # Busco los posee_desc_parts correspondientes a esa norma cuyos
  # descriptores particulares pertenezcan a ese descriptor general.
  #
  # Devuelvo un Array que tienen posee_desc_parts.
  def PoseeDescPart::buscar_por_dg_norma(norma_id, desc_gen_id)
    # No olvidar que si no se incorpora en el select lo siguiente:
    # "SELECT posee_desc_parts"
    # puede devolver mal los datos, principalmente aquellos cuyos campos
    # sean de nombres idénticos.
    # Asegurarse que los datos que devuelve un "SELECT * ..." sean correctos.
    # En este caso, no lo son pues si no se hubiese corregido este select,
    # devolvería el id de posee_descriptor con el mismo número que el id del
    # descriptor particular.
    PoseeDescPart.find(:all,
      :select => "posee_desc_parts.*",
      :conditions => "norma_id = " + norma_id.to_s + " AND
descriptor_particular_id = descriptor_particulars.id AND
descriptor_particulars.descriptor_general_id = " + desc_gen_id.to_s,
      :from => "posee_desc_parts, descriptor_particulars")
  end

  # Elimino todas las tuplas de mi tabla(_posee_desc_part_) que estén
  # relacionadas con la norma dada por +norma_id+.
  # En otras palabras, elimino las tuplas que posean como valor para el campo
  # "_norma_id_" el id dado por el parámetro +norma_id+.
  #
  def PoseeDescPart::eliminar_relaciones_por_norma(norma_id)
    PoseeDescPart.delete_all(["norma_id = ?",norma_id])
  end

end

app/controllers/posee_desc_parts_controller.rb
class PoseeDescPartsController < ApplicationController
  before_action :set_posee_desc_part, only: [:show, :edit, :update, :destroy]

  # GET /posee_desc_parts
  # GET /posee_desc_parts.json
  def index
    @posee_desc_parts = PoseeDescPart.all
  end

  # GET /posee_desc_parts/1
  # GET /posee_desc_parts/1.json
  def show
  end

  # GET /posee_desc_parts/new
  def new
    @posee_desc_part = PoseeDescPart.new
  end

  # GET /posee_desc_parts/1/edit
  def edit
  end

  # POST /posee_desc_parts
  # POST /posee_desc_parts.json
  def create
    @posee_desc_part = PoseeDescPart.new(posee_desc_part_params)

    respond_to do |format|
      if @posee_desc_part.save
        format.html { redirect_to @posee_desc_part, notice: 'Posee desc part was successfully created.' }
        format.json { render :show, status: :created, location: @posee_desc_part }
      else
        format.html { render :new }
        format.json { render json: @posee_desc_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posee_desc_parts/1
  # PATCH/PUT /posee_desc_parts/1.json
  def update
    respond_to do |format|
      if @posee_desc_part.update(posee_desc_part_params)
        format.html { redirect_to @posee_desc_part, notice: 'Posee desc part was successfully updated.' }
        format.json { render :show, status: :ok, location: @posee_desc_part }
      else
        format.html { render :edit }
        format.json { render json: @posee_desc_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posee_desc_parts/1
  # DELETE /posee_desc_parts/1.json
  def destroy
    @posee_desc_part.destroy
    respond_to do |format|
      format.html { redirect_to posee_desc_parts_url, notice: 'Posee desc part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posee_desc_part
      @posee_desc_part = PoseeDescPart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def posee_desc_part_params
      params.require(:posee_desc_part).permit(:norma_id, :descriptor_particular_id)
    end
end

app/helpers/posee_desc_parts_helper.rb
module PoseeDescPartsHelper
end

app/views/posee_desc_parts/_form.html.erb
<%= form_with(model: posee_desc_part, local: true) do |form| %>
  <% if posee_desc_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posee_desc_part.errors.count, "error") %> prohibited this posee_desc_part from being saved:</h2>

      <ul>
      <% posee_desc_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :norma_id %>
    <%= form.text_field :norma_id %>
  </div>

  <div class="field">
    <%= form.label :descriptor_particular_id %>
    <%= form.text_field :descriptor_particular_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posee_desc_parts/edit.html.erb
<h1>Editing Posee Desc Part</h1>

<%= render 'form', posee_desc_part: @posee_desc_part %>

<%= link_to 'Show', @posee_desc_part %> |
<%= link_to 'Back', posee_desc_parts_path %>

app/views/posee_desc_parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posee Desc Parts</h1>

<table>
  <thead>
    <tr>
      <th>Norma</th>
      <th>Descriptor particular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posee_desc_parts.each do |posee_desc_part| %>
      <tr>
        <td><%= posee_desc_part.norma %></td>
        <td><%= posee_desc_part.descriptor_particular %></td>
        <td><%= link_to 'Show', posee_desc_part %></td>
        <td><%= link_to 'Edit', edit_posee_desc_part_path(posee_desc_part) %></td>
        <td><%= link_to 'Destroy', posee_desc_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posee Desc Part', new_posee_desc_part_path %>

app/views/posee_desc_parts/new.html.erb
<h1>New Posee Desc Part</h1>

<%= render 'form', posee_desc_part: @posee_desc_part %>

<%= link_to 'Back', posee_desc_parts_path %>

app/views/posee_desc_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Norma:</strong>
  <%= @posee_desc_part.norma %>
</p>

<p>
  <strong>Descriptor particular:</strong>
  <%= @posee_desc_part.descriptor_particular %>
</p>

<%= link_to 'Edit', edit_posee_desc_part_path(@posee_desc_part) %> |
<%= link_to 'Back', posee_desc_parts_path %>